FROM python:3.11-slim

WORKDIR /app

RUN pip install poetry
RUN poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock ./

RUN poetry install --only download

COPY /scripts ./scripts

CMD ["python", "scripts/download_files.py"]


